"""Transcribe an EGX index-constituents workbook into ``config/universe.yaml``.

``memory/NEXT_TASK.md`` (M0) states the rule this module exists to enforce:
*never fill the constituent list from memory or recall*. A script that reads the
bytes of a source file and prints the YAML is the cheapest possible proof that
the rule was kept — the diff it produces can be regenerated by anyone holding the
same workbook, and any typed-in ticker would fail to reproduce.

It is also the rebalance path. The index is reviewed periodically; when the next
constituents file arrives, re-run this rather than hand-editing the YAML.

Deterministic and offline despite living in ``research/``: no LLM, no network.
Requires the ``research`` extra (``openpyxl``), which the deterministic core
never imports.

Usage::

    uv run --extra research python -m research.transcribe_universe \\
        memory/sources/EGX33-SHARIAH_constituents_2026-05.xlsx
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from decimal import ROUND_HALF_EVEN, Decimal
from pathlib import Path
from typing import Any

from common.decimals import D

#: The first four headers of the EGX constituents export, in order. A layout
#: change must stop the run rather than silently transcribe the wrong columns.
EXPECTED_HEADERS: tuple[str, ...] = (
    "SYMBOL_CODE",
    "SYMB_NAME_ARB",
    "SYMB_NAME_ENG",
    "REUTERS_CODE",
)

#: The fifth header carries the as-of date, e.g. "Weight as of 30/04/2026".
_WEIGHT_HEADER = re.compile(r"^\s*weight\s+as\s+of\s+(\d{2})/(\d{2})/(\d{4})\s*$", re.IGNORECASE)

#: Excel stores weights as binary floats, so an exact 15% cap arrives as
#: 0.1500000000000203. Eight decimal places is far finer than any index weight
#: is published to and absorbs that noise without discarding real precision.
_WEIGHT_PLACES = Decimal("0.00000001")

#: Tolerance for the transcribed weights summing to the workbook's own total row.
_SUM_TOLERANCE = Decimal("0.000001")

#: Listings that are two share classes of ONE issuer, mapped to their primary
#: ticker. Not a heuristic: the source rows name themselves, in both languages,
#: as the same bank in two currencies —
#:   FAIT.CA  "بنك فيصل الاسلامي المصرية بالجنية" / "Faisal Islamic Bank of Egypt - In EGP"
#:   FAITA.CA "بنك فيصل الاسلامي المصري - بالدولار" / "Faisal Islamic Bank of Egypt - In US Dollars"
#: The grouping matters because concentration limits apply per issuer: treating
#: these as two companies would let one bank hold two full position slots.
#: Any listing not named here is its own issuer.
DUAL_LISTINGS: dict[str, str] = {"FAITA": "FAIT"}


class TranscriptionError(RuntimeError):
    """The workbook does not have the shape this transcriber requires."""


@dataclass(frozen=True)
class SourceRow:
    """One data row, exactly as the workbook holds it."""

    isin: str
    name_ar: str
    name_en: str
    reuters_code: str
    weight: Decimal


@dataclass(frozen=True)
class Transcription:
    """The workbook's full contents, verified against its own total row."""

    as_of: str
    rows: tuple[SourceRow, ...]
    declared_total: Decimal | None

    @property
    def issuer_count(self) -> int:
        return len({issuer_id(r.reuters_code) for r in self.rows})


def ticker_of(reuters_code: str) -> str:
    """``"TMGH.CA  "`` -> ``"TMGH"``. Whitespace and the venue suffix only."""
    return reuters_code.strip().split(".")[0].strip().upper()


def issuer_id(reuters_code: str) -> str:
    """The issuer a listing belongs to — itself, unless it is a known dual listing."""
    ticker = ticker_of(reuters_code)
    return DUAL_LISTINGS.get(ticker, ticker)


def parse_as_of(header: Any) -> str:
    """Read the as-of date out of the weight column header, as ISO ``YYYY-MM-DD``.

    The date is metadata we must capture, not assume: weights drift between
    rebalances, so a weight without its date is not interpretable.
    """
    match = _WEIGHT_HEADER.match(str(header or ""))
    if not match:
        raise TranscriptionError(
            f"weight column header {header!r} does not match 'Weight as of DD/MM/YYYY' — "
            "refusing to guess the as-of date"
        )
    day, month, year = match.groups()
    return f"{year}-{month}-{day}"


def _quantise(weight: Decimal) -> Decimal:
    return weight.quantize(_WEIGHT_PLACES, rounding=ROUND_HALF_EVEN)


def parse_rows(records: Iterable[Sequence[Any]]) -> Transcription:
    """Turn raw worksheet rows into a verified :class:`Transcription`.

    Pure: takes plain tuples so it is testable without a real workbook.
    """
    records = list(records)
    if not records:
        raise TranscriptionError("worksheet is empty")

    header = records[0]
    if len(header) < 5:
        raise TranscriptionError(f"expected at least 5 columns, found {len(header)}")
    actual = tuple(str(h or "").strip() for h in header[:4])
    if actual != EXPECTED_HEADERS:
        raise TranscriptionError(f"unexpected column layout: {actual} != {EXPECTED_HEADERS}")
    as_of = parse_as_of(header[4])

    rows: list[SourceRow] = []
    declared_total: Decimal | None = None
    for number, record in enumerate(records[1:], start=2):
        cells = [c if c is not None else "" for c in record]
        isin = str(cells[0]).strip()
        weight_cell = record[4] if len(record) > 4 else None

        if not isin:
            # The export ends with a totals row: no identifiers, weight = 1.
            # Keep it as the cross-check rather than discarding it.
            if weight_cell is not None and declared_total is None:
                declared_total = D(weight_cell)
                continue
            raise TranscriptionError(f"row {number} has no SYMBOL_CODE and is not a total row")

        if weight_cell is None:
            raise TranscriptionError(f"row {number} ({isin}) has no weight")
        reuters = str(cells[3]).strip()
        if not reuters:
            raise TranscriptionError(f"row {number} ({isin}) has no REUTERS_CODE")
        rows.append(
            SourceRow(
                isin=isin,
                name_ar=str(cells[1]).strip(),
                name_en=str(cells[2]).strip(),
                reuters_code=reuters,
                weight=_quantise(D(weight_cell)),
            )
        )

    if not rows:
        raise TranscriptionError("worksheet contains a header but no constituents")

    if declared_total is not None:
        total = sum((r.weight for r in rows), start=Decimal(0))
        if abs(total - declared_total) > _SUM_TOLERANCE:
            raise TranscriptionError(
                f"transcribed weights sum to {total} but the workbook's total row says "
                f"{declared_total} — the transcription is incomplete or misaligned"
            )
    return Transcription(as_of=as_of, rows=tuple(rows), declared_total=declared_total)


def read_workbook(path: Path) -> Transcription:
    """Read the first worksheet of an ``.xlsx`` file. Requires the ``research`` extra."""
    from openpyxl import load_workbook  # imported lazily: optional dependency

    workbook = load_workbook(path, data_only=True, read_only=True)
    try:
        worksheet = workbook.worksheets[0]
        return parse_rows(list(worksheet.iter_rows(values_only=True)))
    finally:
        workbook.close()


def sha256_of(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _yaml_quote(value: str) -> str:
    """Double-quote a scalar. Arabic names contain commas and dashes that would
    otherwise make a bare scalar ambiguous; UTF-8 is preserved verbatim (§7)."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_constituents(transcription: Transcription) -> str:
    """Render the ``constituents:`` block, ready to paste into the YAML."""
    lines = ["constituents:"]
    for row in transcription.rows:
        lines.extend(
            [
                f"  - ticker: {ticker_of(row.reuters_code)}",
                f"    isin: {row.isin}",
                f"    name_en: {_yaml_quote(row.name_en)}",
                f"    name_ar: {_yaml_quote(row.name_ar)}",
                f"    reuters_code: {row.reuters_code.strip()}",
                f"    issuer_id: {issuer_id(row.reuters_code)}",
                f"    index_weight: {row.weight}",
                "    sector: null",
            ]
        )
    return "\n".join(lines)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("workbook", type=Path, help="path to the constituents .xlsx")
    args = parser.parse_args(argv)

    transcription = read_workbook(args.workbook)
    print(f"# source:   {args.workbook}")
    print(f"# sha256:   {sha256_of(args.workbook)}")
    print(f"# as_of:    {transcription.as_of}")
    print(f"# listings: {len(transcription.rows)}  issuers: {transcription.issuer_count}")
    print(render_constituents(transcription))
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
